# Generated by Django 4.2.30 on 2026-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_CRUD', '0002_rename_studentdetails_studentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
